project:
  type: website
  output-dir: docs
website:
  title: "ppuppou blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ppuppou
      - icon: instagram
        href: https://instagram.com
format:
  html:
    theme:
      - sketchy
      - brand
    css: styles.css



